### ISSUE TITLE
Can't update picture if have same device id

### ISSUE THREAD

**Issue by funky81** [funky81/pimatic-ip-camera#1]
Picture can't be updated because they using same device id, so when request of data come and plugin try to update the picture, plugin always resolve the request from the same id but first picture that it's found

**Comment by pimagical** [comment]
That's why i can't see any difference if configuring another interval right?

**Comment by funky81** [comment]
already fixed the bugs since https://github.com/funky81/pimatic-ip-camera/commit/bb039aa1db9af8a4f353ac9cbe192487df53e697
